"""Features of the place universe as of the plan's date (PLAN section 3.2).

    python -m nucprob.features

Writes data/processed/features_1956.parquet: one row per settlement with coordinates, one column
per feature of nucprob.features.registry; features_1956_registry.csv, the registry itself
(family, sources, anachronism flag); and data/FEATURES.md, the catalogue of features with their
provenance and coverage by country, which is committed. Coordinates are not features (PLAN
section 3, rules): they enter only the spatial splits and spatial models.
"""

import pandas as pd

from nucprob.features.administrative import administrative
from nucprob.features.geography import geography
from nucprob.features.industry import industry
from nucprob.features.military import military
from nucprob.features.population import population
from nucprob.features.registry import FEATURES
from nucprob.features.transport import transport
from nucprob.paths import DATA, PROCESSED

FAMILIES = [population, administrative, geography, industry, military, transport]


def build(places: pd.DataFrame | None = None) -> pd.DataFrame:
    if places is None:
        places = pd.read_parquet(PROCESSED / "places_1956.parquet")
    places = places[places["has_coords"]].reset_index(drop=True)
    feats = pd.concat([f(places) for f in FAMILIES], axis=1)
    missing = set(FEATURES) - set(feats.columns)
    assert not missing, f"features in the registry but not built: {missing}"
    extra = set(feats.columns) - set(FEATURES)
    assert not extra, f"features built but not in the registry: {extra}"
    return pd.concat([places[["place_id"]], feats[list(FEATURES)]], axis=1)


def registry() -> pd.DataFrame:
    return pd.DataFrame(
        [
            {
                "feature": name,
                "family": f.family,
                "source": f.source,
                "sources": " ".join(f.sources),
                "anachronism": f.anachronism,
                "note": f.note,
            }
            for name, f in FEATURES.items()
        ]
    )


def catalogue(feats: pd.DataFrame, places: pd.DataFrame) -> str:
    """data/FEATURES.md: every feature, its provenance, and its coverage and mean by country
    over the universe (settlements of 10,000 or more)."""
    universe = places.loc[
        places["in_universe"] & places["has_coords"], ["place_id", "country_1956"]
    ]
    df = universe.merge(feats, on="place_id")
    countries = df["country_1956"].value_counts().index.tolist()
    lines = [
        "# Features as of June 1956",
        "",
        "Generated by `python -m nucprob.features` from `nucprob/features/registry.py`; do not",
        "edit by hand. Sources are ids of `data/sources.yaml` or curated tables under",
        "`data/curated/`. *Anachronism* marks later knowledge standing in for 1956 (PLAN section",
        "3.2). The country columns give the mean over the universe (settlements of 10,000+), or a",
        "dash where the feature is missing for the whole country.",
        "",
        f"Universe: {len(df)} settlements ("
        + ", ".join(f"{c} {n}" for c, n in df["country_1956"].value_counts().items())
        + ").",
        "",
        "| Feature | Family | Source | Ids | Anachronism | Note | " + " | ".join(countries) + " |",
        "|" + "---|" * (6 + len(countries)),
    ]
    means = df.groupby("country_1956")[list(FEATURES)].mean()
    for name, f in FEATURES.items():
        cells = []
        for c in countries:
            v = means.at[c, name]
            cells.append("–" if pd.isna(v) else f"{v:.2f}")
        lines.append(
            f"| `{name}` | {f.family} | {f.source} | {', '.join(f.sources)} | "
            f"{'yes' if f.anachronism else ''} | {f.note} | " + " | ".join(cells) + " |"
        )
    return "\n".join(lines) + "\n"


def main() -> None:
    places = pd.read_parquet(PROCESSED / "places_1956.parquet")
    feats = build(places)
    feats.to_parquet(PROCESSED / "features_1956.parquet", index=False)
    registry().to_csv(PROCESSED / "features_1956_registry.csv", index=False)
    (DATA / "FEATURES.md").write_text(catalogue(feats, places), encoding="utf-8")
    print(f"{len(feats)} settlements x {len(FEATURES)} features; catalogue in data/FEATURES.md")


if __name__ == "__main__":
    main()
