"""Summarise the extracted target lists in data/curated/labels into data/INVENTORY.md.

One line per CSV: rows, target countries, provenance, how many rows are flagged as coming
from a secondary source. Run from the repository root: python scripts/inventory.py
"""

from pathlib import Path

import pandas as pd

LABELS = Path("data/curated/labels")
OUT = Path("data/INVENTORY.md")
SCHEMA_COLS = {"plan_id", "planner", "target_country", "plan_year", "provenance", "name_source"}


def summarise(path: Path) -> dict:
    df = pd.read_csv(path)
    row = {"file": path.name, "rows": len(df)}
    if SCHEMA_COLS <= set(df.columns):
        row["planner"] = ", ".join(sorted(df["planner"].dropna().astype(str).unique()))
        row["target_country"] = ", ".join(
            sorted(df["target_country"].dropna().astype(str).unique())
        )
        row["year"] = ", ".join(sorted(df["plan_year"].dropna().astype(str).unique()))
        row["provenance"] = ", ".join(sorted(df["provenance"].dropna().astype(str).unique()))
        notes = df.get("notes", pd.Series(dtype=str)).fillna("").astype(str).str.lower()
        row["secondary_rows"] = int(notes.str.contains("secondary").sum())
        row["selected_0"] = int((df.get("selected") == 0).sum()) if "selected" in df else 0
    else:
        row["planner"] = "(own schema)"
        row["target_country"] = row["year"] = row["provenance"] = ""
        row["secondary_rows"] = row["selected_0"] = ""
    return row


def main() -> None:
    rows = [summarise(p) for p in sorted(LABELS.glob("*.csv"))]
    table = pd.DataFrame(rows)
    lines = [
        "# Data inventory",
        "",
        "Generated by `scripts/inventory.py` from `data/curated/labels/`. Provenance cards for every",
        "source are in `data/notes/`. Raw downloads are in `data/raw/` (not in git).",
        "",
        "| File | Rows | Planner | Target country | Year | Provenance | Secondary rows | Rejected rows |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in table.itertuples(index=False):
        lines.append(
            f"| `{r.file}` | {r.rows} | {r.planner} | {r.target_country} | {r.year} | "
            f"{r.provenance} | {r.secondary_rows} | {r.selected_0} |"
        )
    lines += ["", f"Total: {len(table)} files, {int(table['rows'].sum())} rows.", ""]
    OUT.write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
