"""Summarise the extracted target lists in data/curated/labels into data/INVENTORY.md.

One line per CSV: rows, target countries, provenance, how many rows are flagged as coming
from a secondary source. Run from the repository root: python scripts/inventory.py
"""

from pathlib import Path

import pandas as pd
import yaml

LABELS = Path("data/curated/labels")
OUT = Path("data/INVENTORY.md")
SCHEMA_COLS = {"plan_id", "planner", "target_country", "plan_year", "provenance", "name_source"}


def summarise(path: Path) -> dict:
    df = pd.read_csv(path)
    row = {"file": path.name, "rows": len(df)}
    if SCHEMA_COLS <= set(df.columns):
        row["planner"] = ", ".join(sorted(df["planner"].dropna().astype(str).unique()))
        row["target_country"] = ", ".join(
            sorted(df["target_country"].dropna().astype(str).unique())
        )
        row["year"] = ", ".join(sorted(df["plan_year"].dropna().astype(str).unique()))
        row["provenance"] = ", ".join(sorted(df["provenance"].dropna().astype(str).unique()))
        notes = df.get("notes", pd.Series(dtype=str)).fillna("").astype(str).str.lower()
        row["secondary_rows"] = int(notes.str.contains("secondary").sum())
        row["selected_0"] = int((df.get("selected") == 0).sum()) if "selected" in df else 0
    else:
        row["planner"] = "(own schema)"
        row["target_country"] = row["year"] = row["provenance"] = ""
        row["secondary_rows"] = row["selected_0"] = ""
    return row


def main() -> None:
    rows = [summarise(p) for p in sorted(LABELS.glob("*.csv"))]
    table = pd.DataFrame(rows)
    lines = [
        "# Data inventory",
        "",
        "Generated by `scripts/inventory.py` from `data/curated/labels/`. Provenance cards for every",
        "source are in `data/notes/`. Raw downloads are in `data/raw/` (not in git).",
        "",
        "| File | Rows | Planner | Target country | Year | Provenance | Secondary rows | Rejected rows |",
        "|---|---|---|---|---|---|---|---|",
    ]
    for r in table.itertuples(index=False):
        lines.append(
            f"| `{r.file}` | {r.rows} | {r.planner} | {r.target_country} | {r.year} | "
            f"{r.provenance} | {r.secondary_rows} | {r.selected_0} |"
        )
    lines += ["", f"Total: {len(table)} files, {int(table['rows'].sum())} rows.", ""]
    cards = yaml.safe_load((LABELS / "CATALOGUE.yaml").read_text(encoding="utf-8"))["lists"]
    lines += [
        "## Data cards",
        "",
        "From `data/curated/labels/CATALOGUE.yaml` (checked by `tests/test_catalogue.py`). "
        "Use: training lists are large enough to fit a model; transfer-test lists check whether "
        "a model transfers; validation files hold totals to check against.",
        "",
        "| File | What | Planner → targets, year | Provenance | Selection | Use | Completeness | Caveats | Card |",
        "|---|---|---|---|---|---|---|---|---|",
    ]
    order = {"training": 0, "transfer-test": 1, "validation": 2, "audit": 3, "reference": 4}
    for c in sorted(cards, key=lambda c: (order[c["use"]], str(c["year"]), c["file"])):
        lines.append(
            f"| `{c['file']}` | {c['title']} | {c['planner']} → {c['targets']}, {c['year']} | "
            f"{c['provenance']} | {c['selection']} | {c['use']} | {c['completeness']} | "
            f"{c['caveats']} | {c['card']} |"
        )
    lines.append("")
    OUT.write_text("\n".join(lines))
    print("\n".join(lines))


if __name__ == "__main__":
    main()
