"""Row specification for data/curated/features/uk_military_sites_1980.csv (built by scripts/uk_military_1980_build.py)."""
# Each r(...) call:
# (site, role, unit, country, town, page, from_year, until_year, in_role_1980, decision, note, check_regex, extra=[pages], coord=page|(lat, lon))
# from/until are the years of the ROLE at the site (until blank = still in that role in 1991 or later / today).
# The study date is 30 June 1980.

R = []


def r(site, role, unit, country, town, page, fr, un, inr, dec, note, chk, extra=None, coord=None):
    R.append(
        dict(
            site=site,
            role=role,
            unit=unit,
            country=country,
            town=town,
            page=page,
            from_year=fr,
            until_year=un,
            in_role_1980=inr,
            decision=dec,
            note=note,
            chk=chk,
            extra=extra or [],
            coord=coord,
        )
    )


E, S, W, NI = "England", "Scotland", "Wales", "Northern Ireland"
VB = "V bomber"
RSG = "Regional seat of government"
LIN = "Linesman/Mediator"
UKA = "UKADGE"
THIRD = "Third Air Force"

# ---------------- RAF strike / attack ----------------
r(
    "RAF Waddington",
    "raf_vbomber",
    "Vulcan B.2 wing: Nos. 9, 44, 50 and 101 Squadrons",
    E,
    "Lincoln",
    "RAF Waddington",
    1957,
    1984,
    True,
    "",
    "Vulcans from 1957; the last (50 Sqn, tanker conversion) left in 1984.",
    r"Vulcan",
    [VB],
)
r(
    "RAF Scampton",
    "raf_vbomber",
    "Vulcan B.2: Nos. 35 and 617 Squadrons; No. 27 Squadron (Vulcan SR.2 maritime radar reconnaissance)",
    E,
    "Scampton (Lincoln)",
    "RAF Scampton",
    1958,
    1982,
    True,
    "",
    "Vulcan base 1958-1982 (Blue Steel 1962-1970).",
    r"Vulcan",
    [VB],
)
r(
    "RAF Honington",
    "raf_strike_attack",
    "Buccaneer S.2: No. 208 Squadron, No. 12 Squadron (to Lossiemouth Nov 1980), No. 237 OCU",
    E,
    "Bury St Edmunds",
    "RAF Honington",
    1969,
    1984,
    True,
    "",
    "Buccaneers from 1969; Tornado GR1 (TWCU 1981, No. 9 Sqn 1982) replaced them. V-bomber base earlier (1956-1965).",
    r"Buccaneer",
)
r(
    "RAF Coltishall",
    "raf_strike_attack",
    "Jaguar GR1: Nos. 6, 41 and 54 Squadrons",
    E,
    "Norwich",
    "RAF Coltishall",
    1974,
    2006,
    True,
    "",
    "Jaguar wing from 1974 until the station closed (2006).",
    r"Jaguar",
)
r(
    "RAF Wittering",
    "raf_strike_attack",
    "Harrier GR3: No. 1 Squadron, No. 233 OCU",
    E,
    "Stamford",
    "RAF Wittering",
    1969,
    "",
    True,
    "",
    "Home of the Harrier from 1969; V-bomber base and nuclear weapons store earlier.",
    r"Harrier",
)
r(
    "RAF Lossiemouth (Jaguar OCU)",
    "raf_strike_attack",
    "No. 226 OCU (Jaguar)",
    S,
    "Lossiemouth",
    "RAF Lossiemouth",
    1974,
    1991,
    True,
    "",
    "Jaguar conversion unit with a war role as a reserve squadron.",
    r"226 Operational Conversion Unit|226 OCU",
)
r(
    "RAF Lossiemouth (Buccaneer)",
    "raf_strike_attack",
    "Buccaneer S.2B maritime strike: No. 12 Squadron (1980), No. 208 Squadron (1983)",
    S,
    "Lossiemouth",
    "RAF Lossiemouth",
    1980,
    1994,
    False,
    "The first Buccaneers (No. 12 Squadron, from Honington) arrived in November 1980, after mid-1980; No. 208 followed in July 1983",
    "Same site as the Lossiemouth Jaguar and AEW rows.",
    r"first arriving in November 1980",
)
r(
    "RAF Marham (Tornado)",
    "raf_strike_attack",
    "Tornado GR1: No. 617 Squadron (1983), No. 27 Squadron (1983)",
    E,
    "King's Lynn",
    "RAF Marham",
    1982,
    "",
    False,
    "Tornado GR1 strike squadrons arrived 1982-1983",
    "Same site as the Marham tanker row.",
    r"Tornado",
)
r(
    "RAF Cottesmore (TTTE)",
    "raf_strike_attack",
    "Tri-national Tornado Training Establishment",
    E,
    "Oakham",
    "RAF Cottesmore",
    1980,
    1999,
    False,
    "The TTTE moved in from July 1980 and was officially opened on 29 January 1981: not training crews at mid-1980",
    "",
    r"In July 1980, Cottesmore became home",
)

# ---------------- RAF tankers, AEW, maritime, reconnaissance ----------------
r(
    "RAF Marham",
    "raf_tanker",
    "Victor K.2 tankers: Nos. 55 and 57 Squadrons, No. 232 OCU",
    E,
    "King's Lynn",
    "RAF Marham",
    1966,
    1993,
    True,
    "",
    "Victor tanker base from the mid-1960s until 1993; V-bomber base earlier.",
    r"between 1966 and 1993",
)
r(
    "RAF Lossiemouth (AEW)",
    "raf_aew",
    "No. 8 Squadron, Shackleton AEW.2",
    S,
    "Lossiemouth",
    "RAF Lossiemouth",
    1973,
    1991,
    True,
    "",
    "Shackleton airborne early warning from 1973 until 1991.",
    r"Shackleton",
)
r(
    "RAF Kinloss",
    "raf_maritime",
    "Nimrod MR: Nos. 120, 201 and 206 Squadrons (Kinloss Wing)",
    S,
    "Forres",
    "RAF Kinloss",
    1970,
    2010,
    True,
    "",
    "Nimrod maritime patrol from 1970 (Shackletons earlier, from 1950).",
    r"Nimrod",
)
r(
    "RAF St Mawgan",
    "raf_maritime",
    "Nimrod MR: No. 42 Squadron, No. 236 OCU",
    E,
    "Newquay",
    "RAF St Mawgan",
    1951,
    1992,
    True,
    "",
    "Maritime patrol base (Nimrods from 1969 to 1992); nuclear depth charges for US Navy P-3, RAF Nimrod and Dutch P-3 aircraft were stored at the United States Navy Atomic Weapons Department on the airbase.",
    r"United States Navy Atomic Weapons Department",
)
r(
    "RAF Wyton",
    "raf_reconnaissance",
    "No. 51 Squadron (Nimrod R1 signals intelligence); Canberra PR9 No. 39 Squadron; Canberras of Nos. 100 and 360 Squadrons",
    E,
    "Huntingdon",
    "RAF Wyton",
    1953,
    1995,
    True,
    "",
    "Reconnaissance and electronic intelligence station; Nimrod R1s of No. 51 Squadron from 1974.",
    r"Nimrod R1s",
)

# ---------------- RAF air defence ----------------
r(
    "RAF Leuchars",
    "raf_air_defence",
    "Phantom FG.1: Nos. 43 and 111 Squadrons (QRA North)",
    S,
    "St Andrews",
    "RAF Leuchars",
    1950,
    2014,
    True,
    "",
    "Fighter station from 1950; Phantoms 1969-1989, then Tornado F3.",
    r"Phantom",
)
r(
    "RAF Wattisham",
    "raf_air_defence",
    "Phantom FGR.2: Nos. 23 and 56 Squadrons",
    E,
    "Stowmarket",
    "RAF Wattisham",
    1976,
    1992,
    True,
    "",
    "Fighter station since 1950 (Lightnings earlier); Phantoms of Nos. 23 and 56 Squadrons from February/July 1976 until 1992.",
    r"25 February 1976",
)
r(
    "RAF Coningsby",
    "raf_air_defence",
    "Phantom FGR.2: No. 29 Squadron, No. 228 OCU",
    E,
    "Coningsby",
    "RAF Coningsby",
    1968,
    "",
    True,
    "",
    "Phantom station from 1968; V-bomber base earlier.",
    r"Phantom",
)
r(
    "RAF Binbrook",
    "raf_air_defence",
    "Lightning F.3/F.6: Nos. 5 and 11 Squadrons, LTF",
    E,
    "Market Rasen",
    "RAF Binbrook",
    1965,
    1988,
    True,
    "",
    "Last Lightning base (1965-1988).",
    r"Lightning",
)
r(
    "RAF West Raynham",
    "raf_sam",
    "No. 85 Squadron HQ, Bloodhound Mk 2 SAM",
    E,
    "Fakenham",
    "RAF West Raynham",
    1975,
    1991,
    True,
    "",
    "Bloodhound SAM base after the flying units left; No. 85 Sqn reformed here 1975.",
    r"85 Squadron remained at West Raynham",
)
r(
    "RAF North Coates",
    "raf_sam",
    "No. 85 Squadron flight, Bloodhound Mk 2 SAM",
    E,
    "Grimsby",
    "RAF North Coates",
    1976,
    1990,
    True,
    "",
    "Bloodhound site from 1958; B Flight of No. 85 Squadron March 1976 - April 1990.",
    r"March 1976 – April 1990",
)
r(
    "RAF Bawdsey",
    "raf_sam",
    "No. 85 Squadron flight, Bloodhound Mk 2 SAM",
    E,
    "Felixstowe",
    "RAF Bawdsey",
    1978,
    1990,
    True,
    "",
    "Former Chain Home radar station, re-opened in 1978 as a Bloodhound site; missiles moved to West Raynham in July 1990.",
    r"re-opened in 1978 as a Bloodhound",
)

# ---------------- RAF transport and support ----------------
r(
    "RAF Brize Norton",
    "raf_transport",
    "No. 10 Squadron (VC10 C1); Air Movements",
    E,
    "Carterton",
    "RAF Brize Norton",
    1965,
    "",
    True,
    "",
    "Main strategic air transport base from 1965-67 (Strategic Air Command B-47 base earlier); VC10 tankers of No. 101 Sqn from 1984.",
    r"VC10",
)
r(
    "RAF Lyneham",
    "raf_transport",
    "Hercules C1/C3: Nos. 24, 30, 47 and 70 Squadrons, No. 242 OCU",
    E,
    "Chippenham",
    "RAF Lyneham",
    1967,
    2011,
    True,
    "",
    "Tactical transport (Hercules) base from 1967.",
    r"Hercules",
)
r(
    "RAF Odiham",
    "raf_transport",
    "Support helicopters: No. 33 Squadron (Puma), No. 240 OCU; Chinook from 1981",
    E,
    "Hook",
    "RAF Odiham",
    1960,
    "",
    True,
    "",
    "Support helicopter base (Puma and Wessex in 1980; Chinook from 1981).",
    r"Puma|Chinook",
)
r(
    "RAF Northolt",
    "raf_transport",
    "No. 32 Squadron (communications)",
    E,
    "London (Ruislip)",
    "RAF Northolt",
    1946,
    "",
    True,
    "",
    "Communications squadron for government and military VIPs.",
    r"32 Squadron|32 \(The Royal\)",
)
r(
    "RAF Benson",
    "raf_transport",
    "The Queen's Flight; Andover (No. 115 Squadron radar calibration)",
    E,
    "Wallingford",
    "RAF Benson",
    1946,
    "",
    True,
    "",
    "Home of the Queen's Flight (1946-1995).",
    r"Queen's Flight",
)
r(
    "RAF Aldergrove",
    "raf_transport",
    "Main RAF station in Northern Ireland (No. 72 Squadron Wessex only from 12 November 1981)",
    NI,
    "Antrim",
    "RAF Aldergrove",
    1918,
    2009,
    True,
    "",
    "Main RAF station in Northern Ireland; the airfield is shared with Belfast International Airport. The 1980 helicopter units are not given in the article.",
    r"12 November 1981",
)

# ---------------- Command headquarters ----------------
r(
    "RAF High Wycombe",
    "command_hq",
    "HQ RAF Strike Command; HQ UK Air Forces (CINCUKAIR, NATO)",
    E,
    "High Wycombe",
    "RAF High Wycombe",
    1968,
    "",
    True,
    "",
    "Bomber Command HQ from 1940, Strike Command from 1968; underground operations centre.",
    r"Strike Command",
)
r(
    "Northwood Headquarters",
    "command_hq",
    "C-in-C Fleet (from Sept 1971); NATO Eastern Atlantic and Channel commands; Flag Officer Submarines (from 1978); HQ No. 18 Group RAF",
    E,
    "Northwood (London)",
    "Northwood Headquarters",
    1953,
    "",
    True,
    "",
    "Fleet headquarters from 1971 (NATO maritime HQ from 1953); No. 18 (Maritime) Group from 1969.",
    r"In September 1971",
)
r(
    "RAF Bentley Priory",
    "command_hq",
    "HQ No. 11 Group (air defence); HQ Royal Observer Corps",
    E,
    "Stanmore (London)",
    "RAF Bentley Priory",
    1936,
    2008,
    True,
    "",
    "Air defence group HQ: Fighter Command HQ to 1968, then No. 11 Group.",
    r"11 Group",
)
r(
    "RAF Bawtry",
    "command_hq",
    "HQ No. 1 Group (strike: Vulcans, Buccaneers, Jaguars, Harriers, tankers)",
    E,
    "Bawtry",
    "RAF Bawtry",
    1941,
    1984,
    True,
    "",
    "Bawtry Hall was HQ No. 1 Group from 1941 to 1984 (Bomber Command, then Strike Command); the RAF left in 1986.",
    r"1941–1984",
)
r(
    "Pitreavie Castle (MHQ Rosyth)",
    "command_hq",
    "Maritime HQ Rosyth: Flag Officer Scotland and Northern Ireland; Northern Maritime Air Region; NATO Commander Northern sub-area",
    S,
    "Dunfermline",
    "RAF Pitreavie Castle",
    1938,
    1996,
    True,
    "",
    "Joint naval and RAF maritime headquarters.",
    r"Maritime Headquarters|Maritime",
)
r(
    "Mount Wise (MHQ Plymouth)",
    "command_hq",
    "Royal Navy Maritime Headquarters, Plymouth",
    E,
    "Plymouth",
    "Mount Wise, Plymouth",
    "",
    2004,
    True,
    "",
    "Became the Royal Navy's Maritime Headquarters per the article (which gives no dates or coordinates); coordinates are HMNB Devonport's, about 1 km away.",
    r"Maritime Headquarters",
    coord="HMNB Devonport",
)
r(
    "HQ UK Land Forces (Wilton)",
    "command_hq",
    "HQ United Kingdom Land Forces (C-in-C UKLF)",
    E,
    "Wilton (Salisbury)",
    "Erskine Barracks",
    1972,
    2010,
    True,
    "",
    "Army command HQ for the UK, 1972-1995 as UKLF (then HQ Land Command).",
    r"Land Forces",
)
r(
    "Ministry of Defence Main Building",
    "command_hq",
    "Ministry of Defence, Whitehall; Defence Crisis Management Centre",
    E,
    "London (Westminster)",
    "Ministry of Defence Main Building (United Kingdom)",
    1964,
    "",
    True,
    "",
    "MoD head office since the unified ministry formed in 1964.",
    r"Ministry of Defence",
)
r(
    "Thiepval Barracks",
    "army_hq",
    "HQ 39 Infantry Brigade (from 1970); Army HQ in Lisburn (HQ Northern Ireland)",
    NI,
    "Lisburn",
    "Thiepval Barracks",
    1969,
    "",
    True,
    "",
    "Army barracks and headquarters in Lisburn; the article names HQ Northern Ireland as 39 Brigade's superior HQ but does not date its move to Thiepval.",
    r"In early 1970, the barracks also became home",
)
r(
    "Craigiehall",
    "army_hq",
    "HQ Scotland (Army)",
    S,
    "Edinburgh (South Queensferry)",
    "Craigiehall",
    1939,
    2015,
    True,
    "",
    "Requisitioned by the Army in 1939; Army HQ Scotland until 2015.",
    r"served as the Headquarters of the \[\[British Army\]\] in Scotland",
)
r(
    "Imphal Barracks",
    "army_hq",
    "HQ North East District",
    E,
    "York",
    "Imphal Barracks",
    1967,
    "",
    True,
    "",
    "North East District established at the barracks in 1967 (Northern Command HQ 1958-1972).",
    r"was established at the barracks in 1967",
)
r(
    "Fulwood Barracks",
    "army_hq",
    "HQ North West District",
    E,
    "Preston",
    "Fulwood Barracks",
    1977,
    1991,
    True,
    "",
    "HQ North West District from 1977; 42 (North West) Brigade from 1991.",
    r"North West District\]\] in 1977",
)
r(
    "Copthorne Barracks",
    "army_hq",
    "HQ West Midlands District (renamed Western District in the early 1980s)",
    E,
    "Shrewsbury",
    "Copthorne Barracks",
    1967,
    1991,
    True,
    "",
    "West Midlands District established with HQ here in 1967.",
    r"In 1967 the \[\[Western District",
)

# ---------------- Radar and early warning ----------------
r(
    "RAF Fylingdales",
    "early_warning_radar",
    "BMEWS Site III (ballistic missile early warning, US/UK)",
    E,
    "Pickering (Whitby)",
    "RAF Fylingdales",
    1963,
    "",
    True,
    "",
    "Three radomes operational 1963-1992, then the solid-state phased array.",
    r"BMEWS|Ballistic Missile Early Warning",
)
r(
    "RAF Neatishead",
    "air_defence_radar",
    "Linesman radar head; southern Sector Operations Centre",
    E,
    "Norwich",
    "RAF Neatishead",
    1941,
    2006,
    True,
    "",
    "Main southern air-defence radar and control site.",
    r"Sector Operations Centre|SOC|Type 85",
    [LIN],
)
r(
    "RAF Boulmer",
    "air_defence_radar",
    "Linesman radar head; Control and Reporting Centre",
    E,
    "Alnwick",
    "RAF Boulmer",
    1953,
    "",
    True,
    "",
    "Northern England air-defence radar and control site.",
    r"radar",
    [LIN],
)
r(
    "RAF Staxton Wold",
    "air_defence_radar",
    "Linesman radar head (Type 85)",
    E,
    "Scarborough",
    "RAF Staxton Wold",
    1939,
    "",
    True,
    "",
    "One of the four main Linesman radar sites.",
    r"radar",
    [LIN],
)
r(
    "RAF Bishops Court",
    "air_defence_radar",
    "Linesman radar head",
    NI,
    "Downpatrick",
    "RAF Bishops Court",
    1943,
    1992,
    True,
    "",
    "Air-defence radar station for Northern Ireland and the Irish Sea.",
    r"radar",
    [LIN],
)
r(
    "RAF Buchan",
    "air_defence_radar",
    "Control and Reporting Centre; northern Sector Operations Centre (UKADGE)",
    S,
    "Peterhead",
    "RAF Buchan",
    1952,
    "",
    True,
    "",
    "Northern air-defence radar and control site.",
    r"radar",
    [LIN, UKA],
)
r(
    "RAF Saxa Vord",
    "air_defence_radar",
    "NATO/RAF radar head, Unst (Shetland)",
    S,
    "Unst (Shetland)",
    "RAF Saxa Vord",
    1957,
    2006,
    True,
    "",
    "Most northerly air-defence radar.",
    r"radar",
    [LIN, UKA],
)
r(
    "RAF Benbecula",
    "air_defence_radar",
    "Air-defence radar (South Clettraval, North Uist) with a control and reporting centre at Benbecula airfield",
    S,
    "Lochmaddy (North Uist)",
    "RRH Benbecula",
    1980,
    "",
    True,
    'In: the Linesman article lists Benbecula among the northern radars voice-told into L1, but RRH Benbecula gives only "built 1980" and no month',
    "Point is the radar head on North Uist (RRH Benbecula article), about 20 km from the airfield.",
    r"Start date\|1980",
    ["RAF Benbecula", LIN, UKA],
)
r(
    "RAF West Drayton",
    "air_defence_radar",
    "Linesman L1 central processing and control site; London ATC centre (Mediator)",
    E,
    "West Drayton (London)",
    "RAF West Drayton",
    1963,
    2008,
    True,
    "",
    "Central data-processing hub of Linesman per the Linesman article.",
    r"Linesman|L1",
    [LIN],
)
r(
    "RAF Portreath",
    "air_defence_radar",
    "Radar head, Cornwall",
    E,
    "Portreath",
    "RAF Portreath",
    1980,
    "",
    False,
    "The RAF re-opened it as a staffed radar station (a Control and Reporting Post) in October 1980, after mid-1980; Chemical Defence Establishment site c.1950-1980",
    "",
    r"staffed radar station in October 1980",
    [LIN, UKA],
)

# ---------------- Communications and intelligence ----------------
r(
    "GCHQ Cheltenham",
    "comms_intel",
    "Government Communications Headquarters (Oakley and Benhall sites)",
    E,
    "Cheltenham",
    "GCHQ",
    1951,
    "",
    True,
    "",
    "GCHQ moved to Cheltenham 1951-1952.",
    r"Cheltenham",
)
r(
    "GCHQ Bude",
    "comms_intel",
    "Satellite interception station (Composite Signals Organisation Station Morwenstow)",
    E,
    "Bude (Morwenstow)",
    "GCHQ Bude",
    1974,
    "",
    True,
    "",
    "Built on the former RAF Cleave airfield; operational 1974.",
    r"Morwenstow|satellite",
)
r(
    "GCHQ Scarborough",
    "comms_intel",
    "Signals intelligence station (Irton Moor)",
    E,
    "Scarborough",
    "GCHQ Scarborough",
    1943,
    "",
    True,
    "",
    "Oldest continuous signals intercept station.",
    r"Scarborough",
)
r(
    "RAF Menwith Hill",
    "comms_intel",
    "US NSA intelligence station (Field Station Menwith Hill)",
    E,
    "Harrogate",
    "RAF Menwith Hill",
    1954,
    "",
    True,
    "",
    "US Army Security Agency until 1966, NSA thereafter; satellite ground station.",
    r"National Security Agency|NSA",
)
r(
    "RAF Chicksands",
    "comms_intel",
    "USAF Security Service 6950th Electronic Security Group (FLR-9 array)",
    E,
    "Shefford",
    "RAF Chicksands",
    1950,
    1995,
    True,
    "",
    "US signals intelligence station 1950-1995.",
    r"FLR-9|Security Service",
)
r(
    "RAF Croughton",
    "comms_intel",
    "USAF communications relay (2130th Communications Group)",
    E,
    "Brackley",
    "RAF Croughton",
    1950,
    "",
    True,
    "",
    "US strategic communications station.",
    r"[Cc]ommunications",
)
r(
    "RAF Edzell",
    "comms_intel",
    "US Naval Security Group Activity (FLR-9 array)",
    S,
    "Brechin",
    "RAF Edzell",
    1960,
    1997,
    True,
    "",
    "US Navy signals intelligence station 1960-1997.",
    r"Naval Security Group|U\.?S\.? Navy",
)
r(
    "RAF Digby",
    "comms_intel",
    "RAF signals intelligence station",
    E,
    "Sleaford",
    "RAF Digby",
    1955,
    "",
    True,
    "",
    "Flying ceased 1953; today a joint signals intelligence station. The article does not date the signals role, so 1955 is from general knowledge (No. 399 Signals Unit).",
    r"Joint signals intelligence station",
)
r(
    "RAF Oakhanger",
    "comms_intel",
    "Skynet military satellite ground station",
    E,
    "Bordon",
    "RAF Oakhanger",
    1969,
    "",
    True,
    "",
    "Satellite control station from 1969.",
    r"Skynet|satellite",
)
r(
    "NAVFAC Brawdy (RAF Brawdy)",
    "comms_intel",
    "US Naval Facility Brawdy (SOSUS ocean surveillance terminal)",
    W,
    "Haverfordwest",
    "RAF Brawdy",
    1974,
    1995,
    True,
    "",
    "SOSUS shore station on the RAF/RN airfield; the airfield had Hawk training units (Nos. 1 and 2 TWU) in 1980.",
    r"SOSUS|Naval Facility",
)
r(
    "Anthorn Radio Station",
    "comms_intel",
    "VLF transmitter for submarine communications (NATO/Royal Navy)",
    E,
    "Wigton (Anthorn)",
    "Anthorn Radio Station",
    1964,
    "",
    True,
    "",
    "Built on the former RNAS Anthorn; NATO VLF station from 1964.",
    r"VLF|[Ss]ubmarine",
)
r(
    "Criggion Radio Station",
    "comms_intel",
    "VLF transmitter (GBZ) for submarine communications",
    W,
    "Welshpool",
    "Criggion Radio Station",
    1942,
    2003,
    True,
    "",
    "Long-wave/VLF station used for submarine broadcasts.",
    r"VLF|[Ss]ubmarine",
)
r(
    "Rugby Radio Station",
    "comms_intel",
    "VLF transmitter (GBR) for naval communications",
    E,
    "Rugby",
    "Rugby Radio Station",
    1926,
    2003,
    True,
    "",
    "GBR VLF broadcast to submarines.",
    r"GBR|VLF|[Ss]ubmarine",
)
r(
    "HMS Inskip",
    "comms_intel",
    "Royal Navy wireless transmitting station",
    E,
    "Preston (Inskip)",
    "HMS Inskip",
    1958,
    "",
    True,
    "",
    "RN HF transmitting station on a former airfield.",
    r"[Rr]adio|[Ww]ireless|transmit",
)
r(
    "RAF Daws Hill",
    "comms_intel",
    "USAF High Wycombe Air Station (command bunker and communications)",
    E,
    "High Wycombe",
    "RAF Daws Hill",
    1952,
    2009,
    True,
    "",
    "US station beside HQ Strike Command; the article dates its nuclear command bunker (direction of bombers and cruise missiles) to the 1980s, so its 1980 role is uncertain.",
    r"during the 1980s, housing a \[\[nuclear bunker",
)

# ---------------- USAF in the UK ----------------
r(
    "RAF Lakenheath",
    "usaf_strike",
    "48th Tactical Fighter Wing (F-111F)",
    E,
    "Brandon (Lakenheath)",
    "RAF Lakenheath",
    1960,
    "",
    True,
    "",
    "48th TFW from 1960; F-111F from 1977.",
    r"F-111\]\]s in June 1977",
)
r(
    "RAF Upper Heyford",
    "usaf_strike",
    "20th Tactical Fighter Wing (F-111E)",
    E,
    "Bicester",
    "RAF Upper Heyford",
    1970,
    1993,
    True,
    "",
    "F-111E from 1970; EF-111A of the 42nd ECS from 1984.",
    r"from 1970 \[\[General Dynamics F-111",
)
r(
    "RAF Bentwaters",
    "usaf_attack",
    "81st Tactical Fighter Wing (A-10A from 1979)",
    E,
    "Woodbridge",
    "RAF Bentwaters",
    1951,
    1993,
    True,
    "",
    "81st TFW from 1951; A-10 from 1979 (F-4 Phantom earlier).",
    r"A-10",
)
r(
    "RAF Woodbridge",
    "usaf_attack",
    "81st TFW A-10A squadrons; 67th Aerospace Rescue and Recovery Squadron",
    E,
    "Woodbridge",
    "RAF Woodbridge",
    1952,
    1993,
    True,
    "",
    "Twin base of Bentwaters.",
    r"A-10|67th",
)
r(
    "RAF Mildenhall",
    "usaf_command_transport",
    "HQ Third Air Force (from 15 April 1972); 513th Tactical Airlift Wing (EC-135H Silk Purse airborne command post); Det 4, 9th SRW (rotational SR-71/U-2 from 1976)",
    E,
    "Mildenhall",
    "RAF Mildenhall",
    1959,
    "",
    True,
    "",
    "USAF transport hub (UK passenger terminal from 1958); Third Air Force HQ 1972-2005.",
    r"Mildenhall\]\], England, 15 April 1972",
    [THIRD],
)
r(
    "RAF Alconbury",
    "usaf_reconnaissance",
    "10th Tactical Reconnaissance Wing (RF-4C); 527th Aggressor Squadron (F-5E)",
    E,
    "Huntingdon",
    "RAF Alconbury",
    1959,
    1993,
    True,
    "",
    "RF-4C until 1987; U-2/TR-1 of the 17th Reconnaissance Wing from 1983.",
    r"RF-4C|10th",
)
r(
    "RAF Fairford",
    "usaf_tanker",
    "11th Strategic Group (KC-135 European Tanker Task Force)",
    E,
    "Fairford",
    "RAF Fairford",
    1979,
    1990,
    True,
    "",
    "SAC tanker deployments from 1979 (Concorde test base 1969-1977).",
    r"KC-135",
)
r(
    "RAF Sculthorpe",
    "usaf_standby",
    "USAF reserve base (Det 1, 48th TFW); visiting and exercise deployments",
    E,
    "Fakenham",
    "RAF Sculthorpe",
    1962,
    1992,
    True,
    "",
    "No aircraft permanently based after the 47th BW left in 1962; temporary deployments 1962-1992.",
    r"Temporary Deployments \(1962 - 1992\)",
)
r(
    "RAF Wethersfield",
    "usaf_standby",
    "USAF reserve airfield",
    E,
    "Braintree",
    "RAF Wethersfield",
    1970,
    1993,
    True,
    "",
    "USAF fighter airfield until 1970, then held as a reserve airfield until 1993.",
    r"held as a reserve airfield until 1993",
)
r(
    "RAF Greenham Common",
    "usaf_support",
    "USAF site under the 7551st Combat Support Group (mail sorting and storage); International Air Tattoo from 1973",
    E,
    "Newbury",
    "RAF Greenham Common",
    1964,
    1992,
    True,
    "",
    "After SAC left in 1964 the site was mainly a USAF mail sorting and storage facility. In June 1980 it was selected as one of two British GLCM bases (the Molesworth and GLCM rows).",
    r"in June 1980, RAF Greenham Common was selected",
)
r(
    "RAF Greenham Common (GLCM)",
    "usaf_glcm",
    "501st Tactical Missile Wing (BGM-109G Gryphon)",
    E,
    "Newbury",
    "RAF Greenham Common",
    1982,
    1991,
    False,
    "The 501st Tactical Missile Wing was activated on 1 July 1982; the last GLCMs left in March 1991",
    "Same site as the Greenham Common support row.",
    r"activated at Greenham Common on 1 July 1982",
)
r(
    "RAF Molesworth (GLCM)",
    "usaf_glcm",
    "Ground-launched cruise missile base (303rd Tactical Missile Wing)",
    E,
    "Huntingdon",
    "RAF Molesworth",
    "",
    "",
    False,
    "The flight line closed in 1973 and the cruise missile facilities were built in the early 1980s: not in role in 1980",
    "The article gives no activation year for the missile wing; it is one of the two British GLCM bases.",
    r"flight line facilities were closed in 1973",
)
r(
    "RAF Welford",
    "usaf_munitions",
    "USAF munitions depot",
    E,
    "Newbury",
    "RAF Welford",
    1955,
    "",
    True,
    "",
    "US munitions storage area.",
    r"munition|ammunition|Munition",
)
r(
    "Holy Loch",
    "ssbn_base",
    "US Navy Submarine Squadron 14 (Polaris/Poseidon SSBN tender and floating dock)",
    S,
    "Dunoon (Sandbank)",
    "Holy Loch",
    1961,
    1992,
    True,
    "",
    "US SSBN forward base 1961-1992.",
    r"From 1961 to 1992, it was used as a United States Navy",
)
r(
    "RAF Machrihanish",
    "naval_air",
    "NATO standby airfield; US Navy weapons facility and special warfare unit",
    S,
    "Campbeltown",
    "RAF Machrihanish",
    1960,
    1995,
    True,
    "",
    "NATO master diversion airfield on standby; US Navy detachment.",
    r"NATO|United States Navy|US Navy",
)
r(
    "RAF Burtonwood (US Army depot)",
    "us_army_depot",
    "US Army prepositioned stocks depot",
    E,
    "Warrington",
    "RAF Burtonwood",
    1967,
    1994,
    True,
    "",
    "US Army storage depot after the USAF left; part of the airfield became the M62.",
    r"Army",
)
r(
    "RNPF Caerwent (US Army)",
    "us_army_depot",
    "US Army ammunition/war reserve depot",
    W,
    "Caerwent",
    "RAF Caerwent",
    1967,
    1993,
    True,
    "",
    "Former Royal Naval Propellant Factory used by the US Army.",
    r"United States|US Army|U\.S\. Army|American",
)

# ---------------- Royal Navy ----------------
r(
    "HMNB Clyde (Faslane)",
    "ssbn_base",
    "10th Submarine Squadron (Resolution-class Polaris SSBNs); 3rd Submarine Squadron (SSN)",
    S,
    "Helensburgh (Faslane)",
    "HMNB Clyde",
    1968,
    "",
    True,
    "",
    "Polaris base from 1968.",
    r"Polaris",
)
r(
    "RNAD Coulport",
    "nuclear_weapons_store",
    "Royal Naval Armaments Depot: Polaris warhead storage and missile loading",
    S,
    "Coulport (Helensburgh)",
    "RNAD Coulport",
    1968,
    "",
    True,
    "",
    "Polaris warhead store from 1968.",
    r"in_use\s*= 1968",
)
r(
    "HMNB Devonport",
    "naval_base",
    "Devonport Naval Base and Dockyard; frigate squadrons; submarine refit",
    E,
    "Plymouth",
    "HMNB Devonport",
    1691,
    "",
    True,
    "",
    "Largest naval base in Western Europe.",
    r"Dockyard|dockyard",
)
r(
    "HMNB Portsmouth",
    "naval_base",
    "Portsmouth Naval Base and Dockyard; C-in-C Naval Home Command",
    E,
    "Portsmouth",
    "HMNB Portsmouth",
    1495,
    "",
    True,
    "",
    "Home of the surface fleet.",
    r"Dockyard|dockyard",
)
r(
    "Rosyth Dockyard",
    "naval_shipyard",
    "Royal Naval Dockyard Rosyth (refits of surface ships and submarines)",
    S,
    "Dunfermline",
    "Rosyth Dockyard",
    1916,
    "",
    True,
    "",
    "Royal Navy refit yard until privatisation in the 1990s.",
    r"refitting of \[\[Royal Navy\]\] surface vessels and submarines",
)
r(
    "Chatham Dockyard",
    "naval_shipyard",
    "HM Dockyard Chatham",
    E,
    "Chatham",
    "Chatham Dockyard",
    1567,
    1984,
    True,
    "",
    "Royal dockyard 1567-1984.",
    r"Chatham dockyard closed in 1984",
)
r(
    "HMNB Portland",
    "naval_base",
    "HMS Osprey; Flag Officer Sea Training; Admiralty Underwater Weapons Establishment",
    E,
    "Portland",
    "HMNB Portland",
    1845,
    1995,
    True,
    "",
    "Naval base until 1995.",
    r"Osprey|Sea Training",
)
r(
    "RNAS Yeovilton",
    "naval_air",
    "HMS Heron: Fleet Air Arm (Sea Harrier from 1979-80; Commando helicopters)",
    E,
    "Yeovil",
    "RNAS Yeovilton",
    1940,
    "",
    True,
    "",
    "Main Fleet Air Arm fixed-wing base.",
    r"Sea Harrier",
)
r(
    "RNAS Culdrose",
    "naval_air",
    "HMS Seahawk: anti-submarine Sea King squadrons",
    E,
    "Helston",
    "RNAS Culdrose",
    1947,
    "",
    True,
    "",
    "Largest helicopter base in Europe.",
    r"Sea King",
)
r(
    "RNAS Prestwick",
    "naval_air",
    "HMS Gannet: No. 819 Naval Air Squadron (Sea King ASW, supporting the Clyde SSBNs)",
    S,
    "Prestwick",
    "RNAS Prestwick",
    1971,
    "",
    True,
    "",
    "Anti-submarine helicopters protecting the Clyde.",
    r"819",
)
r(
    "Stonehouse Barracks",
    "royal_marines",
    "HQ 3 Commando Brigade Royal Marines",
    E,
    "Plymouth",
    "Stonehouse Barracks",
    1971,
    "",
    True,
    "",
    "3 Commando Brigade HQ.",
    r"3 Commando Brigade",
)
r(
    "RM Condor",
    "royal_marines",
    "45 Commando Royal Marines (Arctic warfare)",
    S,
    "Arbroath",
    "RM Condor",
    1971,
    "",
    True,
    "",
    "Home of 45 Commando from 1971.",
    r"45 Commando",
)
r(
    "RM Poole",
    "royal_marines",
    "Special Boat Squadron; Royal Marines landing craft",
    E,
    "Poole",
    "RM Poole",
    1954,
    "",
    True,
    "",
    "Home of the SBS.",
    r"Special Boat",
)
r(
    "Barrow-in-Furness shipyard",
    "naval_shipyard",
    "Vickers Shipbuilding and Engineering: nuclear submarine construction",
    E,
    "Barrow-in-Furness",
    "BAE Systems Submarines",
    1871,
    "",
    True,
    "",
    "Builder of the Polaris and SSN submarines; coordinates from the article.",
    r"Vickers",
)
r(
    "Vulcan Naval Reactor Test Establishment",
    "naval_shipyard",
    "HMS Vulcan: naval submarine reactor prototypes",
    S,
    "Thurso (Dounreay)",
    "Vulcan Naval Reactor Test Establishment",
    1965,
    "",
    True,
    "",
    "Prototype submarine reactors beside Dounreay.",
    r"reactor",
)
r(
    "DM Glen Douglas",
    "naval_munitions",
    "NATO munitions depot (Glen Douglas)",
    S,
    "Arrochar",
    "Defence Munitions Glen Douglas",
    1966,
    "",
    True,
    "",
    "Built 1962-1966, in use from 1966.",
    r"in_use\s*= 1966",
)
r(
    "RNAD Ernesettle",
    "naval_munitions",
    "Royal Naval Armaments Depot",
    E,
    "Plymouth",
    "Ernesettle",
    1938,
    "",
    True,
    "",
    "Naval weapons depot serving Devonport.",
    r"[Aa]rmament|[Mm]unition",
)
r(
    "DM Crombie",
    "naval_munitions",
    "Royal Naval Armaments Depot Crombie",
    S,
    "Dunfermline",
    "DM Crombie",
    1916,
    "",
    True,
    "",
    "Naval weapons depot serving Rosyth.",
    r"[Aa]rmament|[Mm]unition",
)
r(
    "RNAD Trecwn",
    "naval_munitions",
    "Royal Naval Armaments Depot",
    W,
    "Fishguard",
    "RNAD Trecwn",
    1938,
    1992,
    True,
    "",
    "Naval mine and munitions depot built 1938; decommissioned 1992.",
    r"Decommissioned in 1992",
)

# ---------------- Nuclear weapons establishments and materials ----------------
r(
    "AWRE Aldermaston",
    "nuclear_weapons_establishment",
    "Atomic Weapons Research Establishment (design, plutonium and uranium components)",
    E,
    "Aldermaston (Reading)",
    "Atomic Weapons Establishment",
    1950,
    "",
    True,
    "",
    "Weapons design and component manufacture from 1950.",
    r"Aldermaston",
)
r(
    "ROF Burghfield",
    "nuclear_weapons_establishment",
    "Royal Ordnance Factory Burghfield (warhead assembly)",
    E,
    "Burghfield (Reading)",
    "ROF Burghfield",
    1954,
    "",
    True,
    "",
    "ROF carrying out part of AWRE's weapons production; renamed AWE Burghfield in 1987. Coordinates are the village article's (the site lies about 1.5 km away).",
    r"AWE Burghfield",
)
r(
    "ROF Cardiff",
    "nuclear_weapons_establishment",
    "Royal Ordnance Factory Cardiff (Llanishen): weapon components",
    W,
    "Cardiff (Llanishen)",
    "ROF Cardiff",
    "",
    1997,
    True,
    "",
    "ROF carrying out part of AWRE's weapons production (AWE article); became AWE Cardiff in 1987 and closed in 1997. The start of its nuclear work is not dated in the cited articles. Coordinates are the Llanishen district article's.",
    r"ROF Burghfield and ROF Cardiff",
)
r(
    "Windscale and Calder Hall",
    "nuclear_materials",
    "Plutonium production and reprocessing (BNFL Windscale; Calder Hall reactors)",
    E,
    "Seascale (Sellafield)",
    "Sellafield",
    1950,
    "",
    True,
    "",
    "Military plutonium from Calder Hall (1956) and reprocessing.",
    r"plutonium",
)
r(
    "Chapelcross",
    "nuclear_materials",
    "Chapelcross reactors (plutonium, tritium)",
    S,
    "Annan",
    "Chapelcross nuclear power station",
    1959,
    2004,
    True,
    "",
    "Military plutonium and tritium production.",
    r"tritium|plutonium",
)
r(
    "Capenhurst",
    "nuclear_materials",
    "Uranium enrichment (BNFL/Urenco)",
    E,
    "Ellesmere Port (Capenhurst)",
    "Capenhurst nuclear site",
    1953,
    1993,
    True,
    "",
    "Enrichment plant from 1953 with military and civil use; military use ceased in 1993 per the article.",
    r"military use of the site ceased in 1993",
)
r(
    "Springfields",
    "nuclear_materials",
    "Nuclear fuel fabrication (BNFL)",
    E,
    "Preston (Salwick)",
    "Springfields",
    1946,
    "",
    True,
    "",
    "Uranium metal and fuel for military and civil reactors.",
    r"fuel",
)

# ---------------- Army garrisons, training areas and depots ----------------
r(
    "Aldershot Garrison",
    "army_garrison",
    'Aldershot Garrison ("Home of the British Army")',
    E,
    "Aldershot",
    "Aldershot Garrison",
    1854,
    "",
    True,
    "",
    "Main army garrison since 1854; the article does not list the 1980 formations.",
    r"Aldershot",
)
r(
    "Catterick Garrison",
    "army_garrison",
    "Catterick Garrison (Royal Corps of Signals training, armoured and infantry units)",
    E,
    "Richmond (Catterick)",
    "Catterick Garrison",
    1915,
    "",
    True,
    "",
    "Largest garrison in the north.",
    r"Catterick",
)
r(
    "Tidworth Camp",
    "army_garrison",
    "Tidworth Garrison (armoured units)",
    E,
    "Tidworth",
    "Tidworth Camp",
    1902,
    "",
    True,
    "",
    "Salisbury Plain garrison.",
    r"Tidworth",
)
r(
    "Bulford Camp",
    "army_garrison",
    "HQ South West District; Bulford Garrison",
    E,
    "Bulford (Salisbury)",
    "Bulford Camp",
    1897,
    "",
    True,
    "",
    "Salisbury Plain garrison; HQ South West District 1967-1995.",
    r"established at the camp in 1967",
)
r(
    "Larkhill",
    "army_garrison",
    "Royal School of Artillery; artillery garrison",
    E,
    "Larkhill (Amesbury)",
    "Larkhill",
    1914,
    "",
    True,
    "",
    "Home of the Royal Artillery.",
    r"Royal School of Artillery",
)
r(
    "Warminster Garrison",
    "army_garrison",
    "School of Infantry; Battle Group Trainer",
    E,
    "Warminster",
    "Warminster Garrison",
    1937,
    "",
    True,
    "",
    "Infantry school on Salisbury Plain.",
    r"School of Infantry|Land Warfare",
)
r(
    "Colchester Garrison",
    "army_garrison",
    "Colchester Garrison",
    E,
    "Colchester",
    "Colchester Garrison",
    1856,
    "",
    True,
    "",
    "Major garrison; the article does not list the 1980 formations.",
    r"Colchester",
)
r(
    "Stirling Lines",
    "army_garrison",
    "22 Special Air Service Regiment at Bradbury Lines",
    E,
    "Hereford",
    "Stirling Lines",
    1960,
    "",
    True,
    "",
    "SAS at Bradbury Lines, Hereford, from 1960 (renamed Stirling Lines in 1984; the regiment later moved to Credenhill). Coordinates are Hereford's, since the article's point is the later Credenhill site.",
    r"renamed in \[\[1984",
    coord="Hereford",
)
r(
    "Royal Military Academy Sandhurst",
    "army_garrison",
    "Royal Military Academy Sandhurst",
    E,
    "Camberley",
    "Royal Military Academy Sandhurst",
    1947,
    "",
    True,
    "",
    "Officer academy; with Camberley Staff College.",
    r"Sandhurst",
)
r(
    "Salisbury Plain Training Area",
    "army_training_area",
    "Salisbury Plain Training Area",
    E,
    "Amesbury",
    "Salisbury Plain Training Area",
    1897,
    "",
    True,
    "",
    "Largest military training area in the UK.",
    r"training",
)
r(
    "Otterburn Training Area",
    "army_training_area",
    "Otterburn Training Area (artillery ranges)",
    E,
    "Otterburn",
    "Otterburn Training Area",
    1911,
    "",
    True,
    "",
    "Second-largest training area.",
    r"training|Training",
)
r(
    "Stanford Training Area",
    "army_training_area",
    "Stanford Training Area (STANTA)",
    E,
    "Thetford",
    "Stanford Training Area",
    1942,
    "",
    True,
    "",
    "Training area in Norfolk.",
    r"training|Training",
)
r(
    "Sennybridge Training Area",
    "army_training_area",
    "Sennybridge Training Area",
    W,
    "Brecon (Sennybridge)",
    "Sennybridge Training Area",
    1939,
    "",
    True,
    "",
    "Main training area in Wales.",
    r"training|Training",
)
r(
    "DM Kineton",
    "military_depot",
    "Central Ammunition Depot Kineton",
    E,
    "Kineton",
    "DM Kineton",
    1941,
    "",
    True,
    "",
    "Army central ammunition depot.",
    r"[Aa]mmunition|[Mm]unition",
)
r(
    "Central Ordnance Depot Bicester",
    "military_depot",
    "Central Ordnance Depot Bicester (largest army stores depot)",
    E,
    "Bicester",
    "MOD Bicester",
    1942,
    "",
    True,
    "",
    "Army logistics depot.",
    r"[Oo]rdnance|[Dd]epot",
)
r(
    "Central Ordnance Depot Donnington",
    "military_depot",
    "Central Ordnance Depot Donnington",
    E,
    "Telford (Donnington)",
    "MOD Donnington",
    1940,
    "",
    True,
    "",
    "Army logistics depot.",
    r"[Oo]rdnance|[Dd]epot",
)
r(
    "Marchwood Military Port",
    "military_port",
    "17 Port Regiment Royal Corps of Transport (military port)",
    E,
    "Southampton (Marchwood)",
    "Marchwood Military Port",
    1943,
    "",
    True,
    "",
    "The Army's sea-mounting port.",
    r"17 Port|[Pp]ort",
)

# ---------------- Government war headquarters ----------------
r(
    "Central Government War Headquarters (Burlington)",
    "government_war_hq",
    "Central Government War HQ (Burlington), Corsham",
    E,
    "Corsham",
    "Central Government War Headquarters",
    1955,
    2004,
    True,
    "",
    "Commissioned 1955; taken over by the MoD on standby in 1991 and decommissioned in December 2004.",
    r"commissioned in 1955",
    [RSG],
)
# The 1968-1980 sub-regional network ("By the time that the Civil Defence Corps was run down in 1968 ... the network was as follows"),
# on care and maintenance in the 1970s; the 1980 review recast it as Regional Government HQs.
CM = (
    "In the sub-regional network as it stood after the Civil Defence Corps was run down in 1968, kept on a care-and-maintenance "
    "basis in the 1970s; a 1980 review called for the network to be recast as Regional Government Headquarters (Regional seat of government article)"
)
FIN = " In the final (late-1980s) network; the network was run down from 1992."
NOTFIN = " Not in the final (late-1980s) network; the source gives no end date."


def rsg(site, region, country, town, page, fr, un, note, chk, coord_is_town=True):
    r(
        site,
        "government_war_hq",
        region,
        country,
        town,
        page,
        fr,
        un,
        True,
        "",
        CM
        + ". "
        + note
        + (
            " Coordinates are those of the place article (no site article)."
            if coord_is_town
            else ""
        ),
        chk,
        [RSG],
    )


rsg(
    "Hexham sub-regional HQ",
    "Region 1 (Northern) sub-regional control",
    E,
    "Hexham",
    "Hexham",
    1968,
    1992,
    "Former hardened cold store." + FIN,
    r"Hexham",
)
rsg(
    "Bempton sub-regional HQ",
    "Region 2 (North East) sub-regional control",
    E,
    "Bempton",
    "Bempton",
    1968,
    "",
    "Former ROTOR bunker." + NOTFIN,
    r"Bempton",
)
rsg(
    "Conisbrough sub-regional HQ",
    "Region 2 (North East) sub-regional control",
    E,
    "Conisbrough",
    "Conisbrough",
    1968,
    "",
    "Former anti-aircraft operations bunker." + NOTFIN,
    r"Conisbrough",
)
rsg(
    "Skendleby sub-regional HQ",
    "Region 3 (North Midlands) sub-regional control",
    E,
    "Skendleby",
    "Skendleby",
    1968,
    1992,
    "Former ROTOR bunker." + FIN,
    r"Skendleby",
)
rsg(
    "Loughborough sub-regional HQ",
    "Region 3 (North Midlands) sub-regional control",
    E,
    "Loughborough",
    "Loughborough",
    1968,
    1992,
    "Former hardened cold store." + FIN,
    r"Loughborough",
)
rsg(
    "Bawburgh sub-regional HQ",
    "Region 4 (Eastern) sub-regional control",
    E,
    "Bawburgh (Norwich)",
    "Bawburgh",
    1968,
    1992,
    "Former ROTOR bunker." + FIN,
    r"Bawburgh",
)
rsg(
    "Hertford sub-regional HQ",
    "Region 4 (Eastern) sub-regional control",
    E,
    "Hertford",
    "Hertford",
    1968,
    1992,
    "Under Sovereign House, a government office block." + FIN,
    r"Hertford",
)
rsg(
    "Kelvedon Hatch",
    "Region 5 (London) sub-regional control",
    E,
    "Brentwood (Kelvedon Hatch)",
    "Kelvedon Hatch Secret Nuclear Bunker",
    1968,
    1992,
    "Deep former ROTOR bunker, decommissioned 1992.",
    r"decommissioned in 1992",
    False,
)
rsg(
    "Basingstoke sub-regional HQ",
    "Region 6 (Southern) sub-regional control",
    E,
    "Basingstoke",
    "Basingstoke",
    1968,
    "",
    "Protected basement under the Civil Service Commission HQ; replaced by Crowborough because of leaks."
    + NOTFIN,
    r"Basingstoke",
)
rsg(
    "Dover Castle",
    "Region 6 (Southern) sub-regional control",
    E,
    "Dover",
    "Dover Castle",
    1968,
    "",
    'Second World War tunnels ("Dumpy" level). The Dover Castle article says the RSG plan there was abandoned, which conflicts with the network list: uncertain.'
    + NOTFIN,
    r"Regional Seat of Government in the event",
    False,
)
rsg(
    "Guildford (Stoughton Barracks) sub-regional HQ",
    "Region 6 (Southern) sub-regional control",
    E,
    "Guildford",
    "Stoughton Barracks",
    1968,
    "",
    "Stoughton Barracks, Guildford." + NOTFIN,
    r"Stoughton",
    False,
)
rsg(
    "Bolt Head sub-regional HQ",
    "Region 7 (South West) sub-regional control",
    E,
    "Salcombe",
    "RAF Bolt Head",
    1968,
    1994,
    "Former ROTOR R6 bunker (Bolt Head/Hope Cove), used until 1994 as a regional seat of government.",
    r"used until 1994",
    False,
)
rsg(
    "Ullenwood sub-regional HQ",
    "Region 7 (South West) sub-regional control",
    E,
    "Cheltenham (Ullenwood)",
    "Ullenwood",
    1968,
    "",
    "Former anti-aircraft control; replaced by a new bunker at Chilmark." + NOTFIN,
    r"Ullenwood",
)
rsg(
    "Brackla Hill sub-regional HQ",
    "Region 8 (Wales) sub-regional control",
    W,
    "Bridgend",
    "Bridgend",
    1968,
    1992,
    "Former ammunition storage bunker at Brackla Hill, Bridgend." + FIN,
    r"Brackla Hill",
)
rsg(
    "Drakelow Tunnels",
    "Region 9 (West Midlands) sub-regional HQ (SRHQ 9.2 in the 1970s)",
    E,
    "Kidderminster",
    "Drakelow Tunnels",
    1961,
    1992,
    "Former underground shadow factory; SRHQ 9.2 in the 1970s and RGHQ 9.2 from 1982." + FIN,
    r"Sub-Regional Headquarters \(SRHQ 9.2\) in the 1970s",
    False,
)
rsg(
    "Swynnerton sub-regional HQ",
    "Region 9 (West Midlands) sub-regional control",
    E,
    "Swynnerton (Stone)",
    "Swynnerton",
    1968,
    1992,
    "Former ammunition store." + FIN,
    r"Swynnerton",
)
rsg(
    "Southport sub-regional HQ",
    "Region 10 (North West) sub-regional control",
    E,
    "Southport",
    "Southport",
    1968,
    "",
    "Under a technical college; abandoned after flooding." + NOTFIN,
    r"Southport",
)
rsg(
    "Belfast regional war room",
    "Region 11 (Northern Ireland) regional war room, Mount Eden Park",
    NI,
    "Belfast",
    "Belfast",
    1960,
    1989,
    "Replaced by a new bunker at Ballymena, operational 1989.",
    r"Mount Eden Park",
)
rsg(
    "Barnton Quarry",
    "Scottish national HQ",
    S,
    "Edinburgh",
    "Barnton Quarry",
    1961,
    1983,
    "Former ROTOR station; operational until the early 1980s, transferred to Lothian Regional Council in 1983.",
    r"remained operational until the early 1980s",
    False,
)
rsg(
    "Anstruther (Scotland's Secret Bunker)",
    "Scottish North Zone HQ",
    S,
    "Anstruther",
    "Scotland's Secret Bunker",
    1961,
    1993,
    "Former ROTOR station (RAF Troywood); decommissioned 1993.",
    r"In 1993, it was decommissioned",
    False,
)
rsg(
    "Kirknewton (East Zone)",
    "Scottish East Zone HQ",
    S,
    "Kirknewton (Edinburgh)",
    "RAF Kirknewton",
    1961,
    "",
    'Former war room at RAF Kirknewton; the station article does not cover the bunker. Scottish arrangements "remained the same" in the 1970s; replaced by Cultybraggan in the final network.',
    r"East Zone using the former war room",
    False,
)
rsg(
    "East Kilbride (West Zone)",
    "Scottish West Zone HQ",
    S,
    "East Kilbride",
    "East Kilbride",
    1961,
    "",
    "Former anti-aircraft control station; replaced by Cultybraggan in the final network.",
    r"West Zone taking over",
)
